<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Bootstrap/**/*.cs" />
    <Compile Remove="Bootstrap/**/obj/**/*.cs" />
    <Compile Remove="Bootstrap/**/bin/**/*.cs" />
    <Compile Remove="GodotAPI/**/*.cs" />
    <Compile Remove="GodotAPI/**/obj/**/*.cs" />
    <Compile Remove="GodotAPI/**/bin/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ILRepack" Version="2.0.48">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
  </ItemGroup>

  <ItemGroup>
      <Reference Include="GodotSharp">
          <HintPath>vendor/GodotSharp.dll</HintPath>
          <Private>false</Private>
      </Reference>
  </ItemGroup>
</Project>