[package]
name = "misaml-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
directories = "6.0.0"
flate2 = "1.1.10"
misaml-pck = { version = "0.1.0", path = "../misaml-pck" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
steamlocate = "2.1.1"
tar = "0.4.46"
ureq = "3.4.2"
